# Generated by Django 6.0.1 on 2026-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('tech', 'Tech'), ('clothes', 'Clothes'), ('food', 'Food'), ('others', 'Others')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
