# Generated by Django 6.0.1 on 2026-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('rooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('area', models.PositiveIntegerField(help_text='Square meters')),
                ('has_garden', models.BooleanField(default=False)),
            ],
        ),
    ]
