# Generated by Django 6.0.1 on 2026-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('speed', models.IntegerField()),
                ('year', models.DateField()),
                ('isbn', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
    ]
