# Generated by Django 6.0.1 on 2026-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('duration_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_number', models.AutoField(primary_key=True, serialize=False)),
                ('homework', models.TextField()),
                ('theme', models.CharField(max_length=50)),
            ],
        ),
    ]
