# Generated by Django 6.0.1 on 2026-01-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('is_spicy', models.BooleanField(default=False)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
